# Generated by Django 6.0.3 on 2026-05-15 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusConnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Notes', 'Notes Requirement'), ('Coding', 'Coding Doubt'), ('Assignment', 'Assignment Help'), ('Updates', 'Classroom Update'), ('Campus Queries', 'Campus Query / Enquiry')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_posts', to='CampusConnect.student')),
            ],
        ),
    ]
