# Generated by Django 4.2.30 on 2026-05-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusConnect', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='USER', max_length=10),
        ),
    ]
