# Generated by Django 4.2.30 on 2026-05-26 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CampusConnect', '0003_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='CampusConnect.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CampusConnect.student')),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CampusConnect.student')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CampusConnect.post')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='helper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_chats', to='CampusConnect.student'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CampusConnect.post'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester_chats', to='CampusConnect.student'),
        ),
    ]
