# Generated by Django 4.2.30 on 2026-05-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CampusConnect', '0004_chatroom_post_status_student_points_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message',
        ),
    ]
