# Generated by Django 4.2.30 on 2026-05-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampusConnect', '0005_rename_text_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Notes', 'Notes Requirement'), ('Coding', 'Coding Doubt'), ('Assignment', 'Assignment Help'), ('Campus Queries', 'Campus Query / Enquiry')], max_length=50),
        ),
    ]
